#!/bin/bash

#PBS -N ffs
#PBS -e ffs.err
#PBS -o ffs.out
#PBS -l nodes=2:ppn=12
#PBS -l walltime=10:00:00
#PBS -V


PBS_O_WORKDIR='/home/eching/LYDG/demo/shockvortx'
         export PBS_O_WORKDIR
### ---------------------------------------
### BEGINNING OF EXECUTION
### ---------------------------------------

echo The master node of this job is `hostname`
echo The working directory is `echo $PBS_O_WORKDIR`
echo This job runs on the following nodes:
echo `cat $PBS_NODEFILE`


### end of information preamble
cd $PBS_O_WORKDIR
mpirun -np 8 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.8 &
mpirun -np 16 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.16 &
### mpirun -np 2 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.3
### mpirun -np 2 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.4
wait
echo "Running MPIEXEC with: $cmd in directory "`pwd`
### $cmd >& $PBS_O_WORKDIR/log
