#!/bin/bash

#PBS -N ffs
#PBS -e ffs.err
#PBS -o ffs.out
#PBS -l nodes=4:ppn=24
#PBS -l walltime=24:00:00
#PBS -V


PBS_O_WORKDIR='/home/eching/LYDG/demo/hit/comp'
         export PBS_O_WORKDIR
### ---------------------------------------
### BEGINNING OF EXECUTION
### ---------------------------------------

echo The master node of this job is `hostname`
echo The working directory is `echo $PBS_O_WORKDIR`
echo This job runs on the following nodes:
echo `cat $PBS_NODEFILE`


### end of information preamble
cd $PBS_O_WORKDIR
mpirun -np 12 -ppn 12 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.12
mpirun -np 24 -ppn 12 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.24
mpirun -np 48 -ppn 12 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.48
###mpirun -np 48 -ppn 12 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.48
###mpirun -np 96 -ppn 12 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.96
###mv gmon.out scalability_results/96proc/gmon.out 
### mpirun -np 2 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.3
### mpirun -np 2 /home/eching/LYDG/build/bin/plydg bump.job >& $PBS_O_WORKDIR/log.$PBS_JOBID.4
###wait
echo "Running MPIEXEC with: $cmd in directory "`pwd`
### $cmd >& $PBS_O_WORKDIR/log
