#!/bin/bash

#PBS -N ffs
#PBS -e ffs.err
#PBS -o ffs.out
#PBS -l nodes=32:ppn=24
#PBS -l walltime=10:00:00
#PBS -V


PBS_O_WORKDIR='/home/eching/LYDG/demo/hit/comp'
         export PBS_O_WORKDIR
### ---------------------------------------
### BEGINNING OF EXECUTION
### ---------------------------------------

echo The master node of this job is `hostname`
echo The working directory is `echo $PBS_O_WORKDIR`
echo This job runs on the following nodes:
echo `cat $PBS_NODEFILE`


### end of information preamble
cd $PBS_O_WORKDIR
cmd="mpirun -np 384 -ppn 12 /home/eching/LYDG/build/bin/plydg bump.job"
###cmd="/home/eching/LYDG/build/bin/lydg bump.job"
echo "Running MPIEXEC with: $cmd in directory "`pwd`
$cmd >& $PBS_O_WORKDIR/log384
mv gmon.out scalability_results/384proc/gmon.out
